[package]
name = "ambiq-hal-sys"
version = "0.1.0"
edition = "2018"
links = "ambiqsrc"

[dependencies]

[build-dependencies]
bindgen = "0.59"
cc = "*"
glob = "*"

[features]
sparkfun-redboard = []
default = ["sparkfun-redboard"]
