[package]
name = "ambiq-hal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.6"
cortex-m = "0.7.3"
panic-halt = { version = "*", optional = true }
cortex-m-rt = { version = "*", optional = true }

[dependencies.ambiq-hal-sys]
path = "../ambiq-hal-sys"
optional = true

[dependencies.ambiq-apollo3-pac]
path = "../pac/apollo3"

[features]
ambiq-sdk = [ "ambiq-hal-sys" ]
sparkfun-redboard = [ "ambiq-hal-sys/sparkfun-redboard" ]
test_examples = ["panic-halt", "cortex-m-rt"]

